### ISSUE TITLE
The retry functionality is wrong

### ISSUE THREAD

**Issue by bstavares** [fjogeleit/http-request-action#142]
The retryWait value is being replaced by retry value in the file [index.js](https://github.com/fjogeleit/http-request-action/blob/main/src/index.js#L59)

```
let retryWait = 3000
if (!!core.getInput('retryWait')) {
  retry = parseInt(core.getInput('retryWait'))
}
```

In the file [helper.js](https://github.com/fjogeleit/http-request-action/blob/main/src/helper.js#L58) the 'retries' variable is not defined anywhere

```
if (i < options.retries) {
      options.actions.warning(`#${i + 1} request failed: ${err}`);
      await sleep(options.sleep);
    }

    i++;
  } while (i <= options.retry);
```

**Comment by fjogeleit** [comment]
thanks, will take a look

**Comment by fjogeleit** [comment]
fixed in latest release

**Comment by bstavares** [comment]
The error still persists of replacing the retry value with the retryWait value in the file [indes.js](https://github.com/fjogeleit/http-request-action/blob/main/src/index.js#L61)

**Comment by fjogeleit** [comment]
hm will check again

**Comment by fjogeleit** [comment]
Fix released
